class RestaurantSerializer < ActiveModel::Serializer
  attributes :id, 
    :yelp_id, 
    :name, 
    :address1, 
    :city, 
    :state, 
    :zip_code, 
    :price, 
    :rating, 
    :image_url, 
    :url,
    :phone,
    :categories, 
    :bottomless_upvote, 
    :bottomless_downvote,
    :reservations_upvote, 
    :reservations_downvote,
    :drink_specials_upvote, 
    :drink_specials_downvote,
    :outdoor_seating_upvote, 
    :outdoor_seating_downvote,
    :drag_downvote,
    :drag_upvote
end
